#!/bin/bash
# Sets up config options for a new system.
# Each set of settings is contained in a submodule; this script simply prompts the user for each script.

source util-functions.sh

modprompt 'Pop_OS' './popos/popos-setup'
