#!/bin/bash
# Sets up config options for a new system.
# Each set of settings is contained in a submodule; this script simply prompts the user for each script.

DIR="$(dirname $0)"
source "$DIR/util-functions.sh"

modprompt 'Pop_OS' "$DIR/popos/popos-setup"
modprompt 'apt install' "$DIR/common-apt-installs/install-common"
modprompt 'vim config' "$DIR/vim/vim-config"
modprompt 'bashrc' "$DIR/bash/install-bashrc"
