#!/bin/bash
# Runs setup for Pop_OS

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/../util-functions.sh


modprompt 'fractional scaling' "$DIR/fractional-scaling"
